FROM python:3.9-alpine

LABEL Maintainer="Valmir Barbosa"

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY tradebot_alpha.py .
COPY data/ data/

EXPOSE 5000
EXPOSE 8000

CMD ["python", "tradebot_alpha.py"]
