services:
  app:
    container_name: trade_bot_app
    hostname: bot-app
    build:
      context: .
      dockerfile: Dockerfile.python
    command: [ "watchmedo", "auto-restart", "--directory=./", "--pattern=*.py", "--recursive", "--", "python", "tradebot_alpha.py" ]
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
      - "8000:8000"
    networks:
      - trade_bot

  anaconda:
    container_name: trade_bot_anaconda
    build:
      context: .
      dockerfile: Dockerfile.anaconda
    volumes:
      - .:/opt/notebooks
    networks:
      - trade_bot
    ports:
      - "8888:8888"

  compile:
    container_name: trade_bot_compile
    build:
      context: .
      dockerfile: Dockerfile.anaconda
    command: [ 'jupyter', 'nbconvert', '--to', 'script', 'tradebot_alpha.ipynb', '--output', 'tradebot_alpha' ]
    restart: "no"
    volumes:
      - .:/opt/notebooks

networks:
  trade_bot:
    driver: bridge


