FROM continuumio/miniconda3:24.3.0-0

RUN /opt/conda/bin/conda install jupyter -y --quiet

RUN mkdir /opt/notebooks && \
    chmod -R 777 /opt/notebooks

WORKDIR /opt/notebooks

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8888

CMD ["/opt/conda/bin/jupyter", "notebook", "--notebook-dir=/opt/notebooks", "--ip='*'", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]

